### ISSUE TITLE
Is there any way to compile this one more often?

### ISSUE THREAD

**Issue by BF3000** [Manuel-K/devilutionX-QOL-patches#1]
Is there any way to compile this one more often?
Quite a few can do on its own.

**Comment by Manuel-K** [comment]
At first I didn't want to provide any binaries at all. Then I was talked into providing binaries of stable releases. 

I've compiled a version of current master with the patches. For now I think the best course if you request a compiled version and I will upload one when I get around to it.

**Comment by BF3000** [comment]
Thanks.
Not like I ask to do it every day.

**Comment by BF3000** [comment]
0.5.0 is out.

**Comment by Manuel-K** [comment]
I've uploaded a new version. It might work.

**Comment by BF3000** [comment]
I works.

**Comment by BF3000** [comment]
1.0.0 is released.

**Comment by Manuel-K** [comment]
I've uploaded a completely untested binary of 1.0.0.

**Comment by AJenbo** [comment]
Your release notes says that it opens a terminal, but that's not true for 1.0.0 so I would think it's not true for your version either

**Comment by Manuel-K** [comment]
We won't find out unless someone tests it.

**Comment by Manuel-K** [comment]
Right. It doesn't open the terminal anymore. I've just booted my desktop PC into Windows which I have been avoiding since my desk lamp broke.

**Comment by BF3000** [comment]
1.0.1 is released.

**Comment by Manuel-K** [comment]
Uploaded a new build. Please confirm if it runs without problems.

**Comment by BF3000** [comment]
Well it works.

**Comment by TheBambino** [comment]
I'm using all patches in 1.0.1. Everything seems to be working great. Much appreciated.

**Comment by Manuel-K** [comment]
Uploaded a new build that has the correct label in the main menu.
