### ISSUE TITLE
Compile for 1.1.0

### ISSUE THREAD

**Issue by malvarenga123** [Manuel-K/devilutionX-QOL-patches#11]
Hi @Manuel-K, can you make a compile for Devilution 1.0.2?

**Comment by AJenbo** [comment]
I would wait a day or so, 1.0.x is our long term branch where only boring stuff happens ;)

**Comment by AJenbo** [comment]
1.1.0 is now released, this would be an excellent time to update the patches :)

**Comment by Manuel-K** [comment]
Thank you for the warning, @AJenbo.

I've rebased the patches on 1.1.0 locally, but I haven't tested anything so far.

**Comment by Manuel-K** [comment]
A compiled Windows version might take some time, because I'll probably have to update my crosscompilation environment (for security reasons).

**Comment by Manuel-K** [comment]
Question: Should I switch to 64-bit builds?

**Comment by AJenbo** [comment]
I still do 32bit Windows build:
- Haven't gotten 64bit cross-compiling for Windows working
- Some users may have 32bit versions of Windows
- 64bit version of Windows always have 32bit support
- The game doesn't need the performance or memory benefits of 64bit computing

**Comment by Manuel-K** [comment]
True.

Everything will take a bit longer. I'm reworking some of the patches. I've already cleaned the monster hp bar patch and made it compatible with the screen resolution changes.

**Comment by Manuel-K** [comment]
I've uploaded a preliminary version of the patches.

**Comment by Manuel-K** [comment]
Oh well, I've managed to shoot my self in the foot with the mixed line endings. Should be fixed now.

**Comment by Manuel-K** [comment]
Here are some binaries for testing. I had to gz the xz compressed files, otherwise github wouldn't let me attach then.

The pre version should be at the current master state.
The pre-tt version makes the red part of the health bar and the item labels transparent and adds tooltips that should make comparison easier to inventory items.
[devilutionx-1.1.0-qol-pre.exe.xz.gz](https://github.com/Manuel-K/devilutionX-QOL-patches/files/5386986/devilutionx-1.1.0-qol-pre.exe.xz.gz)
[devilutionx-1.1.0-qol-pre-tt.exe.xz.gz](https://github.com/Manuel-K/devilutionX-QOL-patches/files/5386990/devilutionx-1.1.0-qol-pre-tt.exe.xz.gz)

**Comment by liPillON** [comment]
thank you Manuel!
I've tried them both without issue (at least as far as I have been able to go through playing)

just wanted to let you know that Windows Defender on my machine detected both files as infected by "Trojan:Win32/Wacatac.C!ml"
that's the only av engine that mark them as positive, though: no alerts from any of the the other av on virustotal.com

**Comment by Manuel-K** [comment]
Compiling anything for Windows is a lot of fun with all the detection heuristics running amok. Maybe going back to the previous cross compilation environment would solve that issue, but it would introduce real security problems.

Please provide feedback whether you prefer the transparent or opaque versions and if the comparison tooltips are useful.

**Comment by liPillON** [comment]
I find the transparent life bars easier on the eyes and yes, the comparison tooltips do come very handy

**Comment by malvarenga123** [comment]
Thanks for the builds @Manuel-K!
I prefer the transparent health bars, but in both versions there is an issue where the townsfolk show a health bar saying "Invalid Monster"
![image](https://user-images.githubusercontent.com/61893389/96202938-fea7ea00-0f36-11eb-95dd-411224be4b70.png)

About the comparison tooltips, I noticed a small mouse lag when moving through items in the inventory and also hard to read when you're using a weapon and a shield. Is there any way to have a fixed-size tooltip with maybe a solid background, like the stone texture used in the inventory?

**Comment by Manuel-K** [comment]
Aha. That's an interesting regression. I didn't catch it because you have to back to town from the dungeon to see the invalid monster bar. I've used separate characters to test. Thank you, @malvarenga123 

[devilutionx-1.1.0-qol-pre2.exe.xz.gz](https://github.com/Manuel-K/devilutionX-QOL-patches/files/5392814/devilutionx-1.1.0-qol-pre2.exe.xz.gz)
[devilutionx-1.1.0-qol-pre2-tt.exe.xz.gz](https://github.com/Manuel-K/devilutionX-QOL-patches/files/5392834/devilutionx-1.1.0-qol-pre2-tt.exe.xz.gz)

>About the comparison tooltips, I noticed a small mouse lag when moving through items in the inventory and also hard to read when you're using a weapon and a shield. Is there any way to have a fixed-size tooltip with maybe a solid background, like the stone texture used in the inventory?

At the moment it's completely unoptimized. I don't think a fixed size would be a good idea – to be on the safe side, it would have to be very wide to accommodate the longest combination of prefixes and suffixes and the height would have to consider all possible unique attributes (6 lines).

I'm thinking about modifying the lookup for equipped items so that it only displays both hand items if the hovered weapon is two-handed; if it's a one-handed weapon it would only display equipped weapon(s) and vice-versa for shields.

**Comment by NeonLightning** [comment]
any chance of a precompiled aarch64 arm or retrofw version of your tooltip test?

**Comment by Manuel-K** [comment]
I'd prefer not to set up another cross compilation environment. 

I could upload Arch Linux builds.

**Comment by NeonLightning** [comment]
makes sense. i'm sure people would appreciate that. i know on one of the systems i use it uses arch.(the main os i use is running void though)

**Comment by Manuel-K** [comment]
That's the current state of things, it has some more changes than the Windows versions, noticeably that it doesn't show equipped shields when hovering over a one-handed weapon and vice-versa.

[devilutionx-1.1.0-qol-pre2-tt2.xz.gz](https://github.com/Manuel-K/devilutionX-QOL-patches/files/5393695/devilutionx-1.1.0-qol-pre2-tt2.xz.gz)

**Comment by AJenbo** [comment]
Damn it doesn't want to load on Ubuntu 20.04 :(
`./devilutionx-1.1.0-qol-pre-tt2: error while loading shared libraries: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory`

**Comment by Manuel-K** [comment]
That's what I expected for distros with non-rolling release model. We could try to figure out which libraries would need to be bundled, use static linking or build against the steam runtime.

**Comment by Manuel-K** [comment]
@AJenbo Some more observations concerning the screenshot text corruption: The item's sprite gets moved in front of the tooltip's text.

**Comment by Manuel-K** [comment]
I've refactored the tooltip code and added centered text. Now the “Equipped” text, the name and the name of the base item are centered. Any opinions?
![screen16](https://user-images.githubusercontent.com/775439/96351002-0abbb500-10b9-11eb-8c36-d67c57e6c7d8.png)
![screen15](https://user-images.githubusercontent.com/775439/96351063-5e2e0300-10b9-11eb-8aed-268454a4bf59.png)

**Comment by AJenbo** [comment]
The draw order is all over the place so it's easy to end up in a situation where you render a thing at a point where it will later be overwritten by another sprite. I'm guessing that is what is happening here.

**Comment by liPillON** [comment]
> I've refactored the tooltip code and added centered text. Now the “Equipped” text, the name and the name of the base item are centered. Any opinions?

the centered text looks good to me
It would be nice however having a bit more opaque background... 
I'd imagine you don't really have much options here..

**Comment by BF3000** [comment]
Look good enough for me.

**Comment by Manuel-K** [comment]
Another round of test builds:
Without tooltips/rmb clicker: [devilutionx-1.1.0-qol-pre3.exe.xz.gz](https://github.com/Manuel-K/devilutionX-QOL-patches/files/5424724/devilutionx-1.1.0-qol-pre3.exe.xz.gz)
With tooltips/without rmb clicker: [devilutionx-1.1.0-qol-pre3-tt.exe.xz.gz](https://github.com/Manuel-K/devilutionX-QOL-patches/files/5424733/devilutionx-1.1.0-qol-pre3-tt.exe.xz.gz)
With tooltips/rmb clicker: [devilutionx-1.1.0-qol-pre3-tt-rmb.exe.xz.gz](https://github.com/Manuel-K/devilutionX-QOL-patches/files/5424744/devilutionx-1.1.0-qol-pre3-tt-rmb.exe.xz.gz)
Arch Linux 64-bit with tooltip/rmb clicker: [devilutionx-1.1.0-qol-pre3-tt-rmb.gz](https://github.com/Manuel-K/devilutionX-QOL-patches/files/5424771/devilutionx-1.1.0-qol-pre3-tt-rmb.gz)

@AJenbo If that build doesn't work, which I expect, you can try the wip patches in the flux branch.

**Comment by BF3000** [comment]
devilutionx-1.1.0-qol-pre3-tt-rmb.exe.xz.gz - virus warnings

**Comment by AJenbo** [comment]
> devilutionx-1.1.0-qol-pre3-tt-rmb.exe.xz.gz - virus warnings

probably mention what tool is reporting it. afaik some tools will basically report anything that isent developed by a big company

**Comment by Manuel-K** [comment]
If you get virus warnings that are probably wrong (aka false positives) you should submit the affected exe to the manufacturer of your AV software. There isn't much I can do about it other than stopping to provide binaries at all.

**Comment by malvarenga123** [comment]
Hi @Manuel-K did you see the latest PR from @qndel? Are your patches the same? I know Infernity was from him.
https://github.com/diasurgical/devilutionX/pull/895

**Comment by qndel** [comment]
my latest patch makes this fork obsolete :)
yep, these patches were ported from infernity and I just ported them myself + cleaned/improved

**Comment by Manuel-K** [comment]
Only two of them are ported from infernity.

**Comment by Manuel-K** [comment]
@malvarenga123 Those patches are not the same. They might have started from the same point.

So to wrap this up:
* You are not the author of the current patches, you are the original author of those infernity patches. The current version is almost a complete rewrite – with the exception of the item label placement modification code.
* It feels like I've wasted all the time to adapt everything to the upstream changes and to recompile my cross-compilation environment for the Windows binaries.
* If I had known that there were any intentions to merge the changes to upstream, I would have gladly cleaned them up even more to get them to standard, but **this casual dismissal without any prior hint isn't a lot of fun**, but it is typical for qndel.

From my perspective it was a huge mistake to invest this lot of time to bring those infernity patches up to scratch again, to start writing the new ones and to waste even more time trying to provide precompiled binaries.

**Comment by qndel** [comment]
> * but **this casual dismissal without any prior hint isn't a lot of fun**, but it is typical for qndel.

huh? it's cool you allowed people to use these things but it was obvious I was going to port them to devilutionx sooner or later, why would I give you any hints? I ported my own code when the time was right 

As for saying only two of them are ported from infernity
https://github.com/qndel/Infernity/commit/11c7c9e584ea8aa69a23c900f027f9edeca16ed8
This looks awfully similar to your running code
Inspired by hellfire you say? ;-)

https://github.com/qndel/Infernity/commit/d24a26653286bd35e773c1e262ec0ce9f8b159c4
Sound after level up

> You are not the author of the current patches, you are the original author of those infernity patches. The current version is almost a complete rewrite – with the exception of the item label placement modification code.

I'd risk saying it's more than just the item label placement code :)
Changing variable names doesn't count as a complete rewrite + you made item highlighting worse than the original

> From my perspective it was a huge mistake to invest this lot of time to bring those infernity patches up to scratch again, to start writing the new ones and to waste even more time trying to provide precompiled binaries.

Dunno what took you so much time, I got all my code to work yesterday in 5 min after literally copy/pasting from infernity.
So yeah, that's a nice thank you I get for making infernity's code public ...

**Comment by AJenbo** [comment]
@qndel he is probably refering to time spend building for various systems and testing.

> From my perspective it was a huge mistake to invest this lot of time to bring those infernity patches up to scratch again, to start writing the new ones and to waste even more time trying to provide precompiled binaries.

People have definitely enjoyed your work, I have seen many mentions on various forums that they prefer it to base DevilutionX. Regarding 1.1.0 specifically, it's worth keeping in mind that it will still be some time before the next release of DevilutionX will be out, meaning that it won't include qndel's recent PR, I know that there are people specifically waiting for your patched version to be out before doing an upgrade to 1.1.0.

Regarding coordination I don't think qndel was really much aware of your work untill I mentioned in when he send his PR.

**Comment by qndel** [comment]
> Regarding coordination I don't think qndel was really much aware of your work untill I mentioned in when he send his PR.

it wouldn't change anything, it's still my good old code with minor changes applied
notice I came here after malvarenga123 mentioned my PR ;)

@Manuel-K 
Let me say it straight, the only thing you did yourself is the clicker, that's nothing to be ashamed of, but don't try to increase your work and diminish mine

**Comment by malvarenga123** [comment]
I don't think it was a waste of time because, as @AJenbo said, many people (including me) prefer this version over the official release. Also, I was under the impression that DevilutionX was a "chocolate" version of Diablo which wouldn't merge such changes.

Maybe there should be a "crispy" version of Diablo where both qndel's and your QOL changes could be released.

**Comment by AJenbo** [comment]
1.0.y versions are chocolate where 1.x.y are crispy. Still, most of the QoL additions will be hidden either behind a flag or a setting.

**Comment by Manuel-K** [comment]
> Let me say it straight, the only thing you did yourself is the clicker, that's nothing to be ashamed of, but don't try to increase your work and diminish mine

I don't agree. Maybe I accidentally misattributed the sound on level up change to sergi4ua, but calling all the rewrites “changing variable names” is very silly. But as I said before, discussing anything with you is a waste of time. I've seen the way you dismiss everything everyone else does in your name calling crusades dozens of times. Therefore this will be last time I write anything about this topic.

I've regretted many times that I based anything on your code – all in all I could have saved a lot of time by starting from scratch.

**Comment by Manuel-K** [comment]
So this is probably the end for this thing. It feels like a huge waste of time and I don't care for that and I don't care for being insulted. Frankly, I've lost any interested in the game for a few months, so I only invested the time to prevent bit rot and not to disappoint the three people using it, but as I wrote before, I seriously regret that.

**Comment by qndel** [comment]
![image](https://user-images.githubusercontent.com/14297035/97864663-3cfc2200-1d09-11eb-8e22-c8b0453e4a10.png)

**Comment by Manuel-K** [comment]
There's the expected meme shitposting. At least it isn't animated.
