### ISSUE TITLE
Import patches from Diablo Torch

### ISSUE THREAD

**Issue by malvarenga123** [Manuel-K/devilutionX-QOL-patches#13]
Hi @Manuel-K, do you know about [Diablo Torch](https://github.com/DiabloTorch/Torch)?
It has a lot of QOL patches for original Diablo that have to be injected after the game is running, like stash, list of shrines and others.

Do you think their patches could be ported to DevilutionX?

**Comment by Manuel-K** [comment]
That would probably need a complete rewrite. 

I'm done with this because I don't want to waste my time and I don't want to be insulted.

**Comment by malvarenga123** [comment]
Sad to hear that. If you have a change of heart, make sure to take a look at Diablo Torch. There are quite a few improvements there.

**Comment by AJenbo** [comment]
@malvarenga123 it looks like @joewis might be continuing the work on QOL patches: https://github.com/joewis/devilutionX-QOL-patches
