### ISSUE TITLE
Some patches don't apply to master (post v0.5.0)

### ISSUE THREAD

**Issue by fredebec** [Manuel-K/devilutionX-QOL-patches#3]
Some patches don't apply successfully with the current (git) version of devilutionX 0.5. It concerns Infernity and run-in-town patches.
Exemple for run_in_town_smooth_01.patch:
`patching file Source/player.cpp
Hunk #1 FAILED at 1207.
1 out of 1 hunk FAILED -- saving rejects to file Source/player.cpp.rej`

**Comment by AJenbo** [comment]
@Manuel-K if you can make a test script for applying thease patches then we could host them upstream and make sure to maintain them with other code changes

**Comment by Manuel-K** [comment]
It should work with the current master. This time there was some more manual intervention necessary in the monster hp bar patch to prevent a segfault.

**Comment by fredebec** [comment]
OK, all patches apply successfully now.
Thanks
