### ISSUE TITLE
Precompiled 1.0 won't run

### ISSUE THREAD

**Issue by NeonLightning** [Manuel-K/devilutionX-QOL-patches#5]
when i try to run the precompiled version it gives this error and then closes.
```
SDL Error
Audio Device hasn't been opened
The error occurred at: SourceX/sound.cpp
line 99
```

**Comment by AJenbo** [comment]
Do you have the same issue with the upstream 1.0.0 ?

**Comment by NeonLightning** [comment]
ran a unsuccessful attempt at patching deviluionx and now its running fine....
