### ISSUE TITLE
Project name patch doesn't apply

### ISSUE THREAD

**Issue by AJenbo** [Manuel-K/devilutionX-QOL-patches#6]
This is no longer statically set.
https://github.com/Manuel-K/devilutionX-QOL-patches/blob/62936e60761bb8a341a9765a33d06d9e890c4425/mk_menu_label_01.patch#L13

Instead it gets applied (taken from CMakeList.txt) here:
https://github.com/diasurgical/devilutionX/blob/c0e511265d775d27028e2014aed333636c85371b/Source/init.cpp#L113

**Comment by Manuel-K** [comment]
Even worse, it says devilutionX-v1.0.0 for 1.0.1.

**Comment by Manuel-K** [comment]
Aha. You moved the tag.

**Comment by Manuel-K** [comment]
Now it says “devilutionX v1.0.0 with QOL changes”. I can't get it to say 1.0.1.

**Comment by AJenbo** [comment]
You have to rerun cmake to pick up the version from git tags.

**Comment by Manuel-K** [comment]
I edited config.h manually.

**Comment by Manuel-K** [comment]
Thank you for the report.

**Comment by AJenbo** [comment]
Sounds good, as just be aware that config.h might be regenerated (based on git) when the CMake cache expires.

**Comment by arrowgent** [comment]
mine just says "DevilutionX v  with QOL changes"

using v1.0.1

**Comment by Manuel-K** [comment]
Are you using a git checkout or did you download an archive of devilutionX? @AJenbo, do you have any idea?
